server:
  port: 9001

mq:
  worker-queue-name: worker

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    org.gol: trace
