server:
  port: 9001

mq:
  worker-queue-name: worker

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    root: info
    org.gol: trace
