server:
  port: ${TOMCAT_PORT:8080}

mq:
  worker-queue-name: ${WORKER_QUEUE_NAME}
  result-consumer:
    concurrency: ${RESULT_LISTENER_CONCURRENCY:1-10}

fib:
  algorithms: ${FIB_ALGORITHMS:ITERATIVE,RECURSIVE,BINETS,EXPONENTIAL}

spring:
  # Artemis broker
  artemis:
    mode: native
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

  # PostgreSQL database
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: ${POSTGRESS_POOL_SIZE:5}
      connection-timeout: ${POSTGRESS_CONNECTION_TIMEOUT:5000}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  jms:
    cache:
      session-cache-size: ${JMS_SESSION_CACHE_SIZE:5}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessSimulator
        readiness:
          include: db, jms, diskSpace

logging:
  level:
    root: info
    org.gol: ${LOGGING_LEVEL:info}
