server:
  port: ${SERVER_PORT}

mq:
  worker-queue-name: ${WORKER_QUEUE_NAME}

spring:
  activemq:
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

logging:
  level:
    root: info
    org.gol: ${LOGGING_LEVEL}
