name: Verify
on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Install dependencies
        run: mvn dependency:go-offline
      - name: Run test suites
        run: mvn --batch-mode clean verify